version: 1
common:
  resourcePath: ./dapr-components
  env:
    DEBUG: 'true'

apps:
  - appID: studyscheduler
    appDirPath: ./Study_Scheduler
    appChannelAddress: localhost
    appProtocol:
    appPort: 8002
    appHealthCheckPath:
    command: ['sh', '-c', 'pip3 install -r requirements.txt && python3 run.py']
  - appID: calendar
    appDirPath: ./calendar
    appChannelAddress: localhost
    appProtocol:
    appPort: 8001
    appHealthCheckPath:
    command: ['java', '-jar', 'target/calendar-0.0.1-SNAPSHOT.jar']
  - appID: academymanager
    appDirPath: ./AcademyManager/AcademyManager
    appChannelAddress: localhost
    appProtocol:
    appPort: 8000
    appHealthCheckPath:
    command: ['dotnet', 'run']
