version: 1
common:
  resourcePath: ./dapr-components
  env:
    DEBUG: 'true'

apps:
  - appID: academyauth
    appDirPath: ./academy_auth
    appChannelAddress: localhost
    appProtocol:
    appPort: 8003
    daprHttpPort: 3503
    appHealthCheckPath:
    command: [
        'sh',
        '-c',
        'curl -fsSL https://bun.sh/install | bash && bun run dev'
      ] # TODO: Fix build stage and change the script to bun run build:start
  - appID: studyscheduler
    appDirPath: ./Study_Scheduler
    appChannelAddress: localhost
    appProtocol:
    appPort: 8002
    daprHttpPort: 3502
    appHealthCheckPath:
    command: ['sh', '-c', 'pip3 install -r requirements.txt && python3 run.py']
  - appID: calendar
    appDirPath: ./calendar
    appChannelAddress: localhost
    appProtocol:
    appPort: 8001
    daprHttpPort: 3501
    appHealthCheckPath:
    command: ['java', '-jar', 'target/calendar-0.0.1-SNAPSHOT.jar']
  - appID: academymanager
    appDirPath: ./AcademyManager/AcademyManager
    appChannelAddress: localhost
    appProtocol:
    appPort: 8000
    daprHttpPort: 3500
    appHealthCheckPath:
    command: ['dotnet', 'run']
