USE [master]
GO

/****** Object:  Database [AcademyManager]    Script Date: 20/06/2023 05:48:37 ******/
CREATE DATABASE [AcademyManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AcademyManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AcademyManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AcademyManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AcademyManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AcademyManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AcademyManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AcademyManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AcademyManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AcademyManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AcademyManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [AcademyManager] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AcademyManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AcademyManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AcademyManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AcademyManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AcademyManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AcademyManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AcademyManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AcademyManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AcademyManager] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AcademyManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AcademyManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AcademyManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AcademyManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AcademyManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AcademyManager] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AcademyManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AcademyManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AcademyManager] SET  MULTI_USER 
GO

ALTER DATABASE [AcademyManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AcademyManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AcademyManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AcademyManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AcademyManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AcademyManager] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AcademyManager] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AcademyManager] SET  READ_WRITE 
GO

